// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAy55rgydpyVyPmwu8GCZfNP2aEJoA7U',
    appId: '1:549524436611:web:5a5034998e69190baa4db6',
    messagingSenderId: '549524436611',
    projectId: 'hairvibe-520c0',
    authDomain: 'hairvibe-520c0.firebaseapp.com',
    storageBucket: 'hairvibe-520c0.appspot.com',
    measurementId: 'G-KXFCJ73QDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjb-xfNlmf3flsOG61As5k1uiDquZFjs',
    appId: '1:549524436611:android:f1fe971fb887dab5aa4db6',
    messagingSenderId: '549524436611',
    projectId: 'hairvibe-520c0',
    storageBucket: 'hairvibe-520c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7luHstOZxaOC9twsJMeGTOyrOAofusTU',
    appId: '1:549524436611:ios:55261163ef6f67e4aa4db6',
    messagingSenderId: '549524436611',
    projectId: 'hairvibe-520c0',
    storageBucket: 'hairvibe-520c0.appspot.com',
    iosBundleId: 'com.example.hairvibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7luHstOZxaOC9twsJMeGTOyrOAofusTU',
    appId: '1:549524436611:ios:55261163ef6f67e4aa4db6',
    messagingSenderId: '549524436611',
    projectId: 'hairvibe-520c0',
    storageBucket: 'hairvibe-520c0.appspot.com',
    iosBundleId: 'com.example.hairvibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAAy55rgydpyVyPmwu8GCZfNP2aEJoA7U',
    appId: '1:549524436611:web:ecd7c82380ea7e5faa4db6',
    messagingSenderId: '549524436611',
    projectId: 'hairvibe-520c0',
    authDomain: 'hairvibe-520c0.firebaseapp.com',
    storageBucket: 'hairvibe-520c0.appspot.com',
    measurementId: 'G-JE21J1GP8S',
  );
}
